"""
Time-series permutation test implementations.

This module provides GPU-accelerated implementations of time-series
permutation tests that preserve temporal structure:

- circle_shift: Circular shift permutation (preserves autocorrelation)
- phase_randomize: FFT-based phase randomization (preserves power spectrum)
- timeseries_correlation_permutation_test: Correlation test with timeseries methods

References:
    Theiler, J., Galdrikian, B., Longtin, A., Eubank, S., & Farmer, J. D. (1991).
    Testing for nonlinearity in time series: the method of surrogate data
    (No. LA-UR-91-3343; CONF-9108181-1). Los Alamos National Lab., NM (United States).

    Lancaster, G., Iatsenko, D., Pidde, A., Ticcinelli, V., & Stefanovska, A. (2018).
    Surrogate data for hypothesis testing of physical systems. Physics Reports, 748, 1-60.
"""

import numpy as np
from typing import Union, Optional, Literal, TYPE_CHECKING
from sklearn.utils import check_random_state

from .utils import _compute_pvalue, _auto_batch_size
from .correlation import (
    _pearson_correlation,
    _spearman_correlation,
    _kendall_correlation,
)
from nltools.backends import Backend

if TYPE_CHECKING:
    import torch


def circle_shift(
    data: np.ndarray,
    shift_amount: Optional[Union[int, np.ndarray]] = None,
    random_state: Optional[Union[int, np.random.RandomState]] = None,
) -> np.ndarray:
    """
    Circular shift for time-series data.

    Performs a circular shift that preserves autocorrelation structure.
    Useful for permutation tests on autocorrelated time series (e.g., fMRI).
    For 1D data, shifts by a single amount. For 2D data, shifts each
    feature (column) independently.

    Args:
        data: Time series data, shape (n_samples,) or (n_samples, n_features)
        shift_amount: Shift amount(s). If None, random shift is used.
            For 1D: int specifying shift amount
            For 2D: array of length n_features with shift per feature
        random_state: Random seed for reproducibility (if shift_amount is None)

    Returns:
        Circularly shifted data with same shape as input

    Examples:
        >>> x = np.array([1, 2, 3, 4, 5])
        >>> circle_shift(x, shift_amount=2)
        array([4, 5, 1, 2, 3])

        >>> X = np.array([[1, 10], [2, 20], [3, 30], [4, 40]])
        >>> circle_shift(X, shift_amount=np.array([1, 2]))
        array([[ 4, 30],
               [ 1, 40],
               [ 2, 10],
               [ 3, 20]])
    """
    data = np.asarray(data)
    rng = check_random_state(random_state)

    # 1D case
    if data.ndim == 1:
        if shift_amount is None:
            shift_amount = rng.choice(np.arange(len(data)), replace=False)
        shift_amount = int(shift_amount)
        return np.concatenate([data[-shift_amount:], data[:-shift_amount]])

    # 2D case
    elif data.ndim == 2:
        n_samples, n_features = data.shape
        if shift_amount is None:
            # Each feature gets an independent random shift (with replacement)
            # This allows n_features > n_samples (e.g., more voxels than timepoints)
            shift_amount = rng.randint(1, n_samples, size=n_features)
        shift_amount = np.asarray(shift_amount, dtype=int)

        if shift_amount.shape != (n_features,):
            raise ValueError(
                f"shift_amount must have length n_features={n_features}, "
                f"got shape {shift_amount.shape}"
            )

        # Shift each feature independently
        shifted = np.empty_like(data)
        for i, shift in enumerate(shift_amount):
            shifted[:, i] = np.concatenate([data[-shift:, i], data[:-shift, i]])
        return shifted

    else:
        raise ValueError(f"data must be 1D or 2D, got shape {data.shape}")


def phase_randomize(
    data: np.ndarray,
    backend: Optional[str] = None,
    random_state: Optional[Union[int, np.random.RandomState]] = None,
) -> np.ndarray:
    """
    FFT-based phase randomization for time-series data.

    Preserves the power spectrum (autocorrelation) but destroys nonlinear
    temporal structure by randomizing Fourier phases. Used to test whether
    data was generated by a linear Gaussian process or contains nonlinear
    dynamics.

    Algorithm:
        1. Compute FFT of input signal
        2. Generate random phases [0, 2π] for positive frequencies
        3. Apply phase shifts to positive frequencies: multiply by exp(i*φ)
        4. Apply conjugate phase shifts to negative frequencies (for real output)
        5. Compute inverse FFT to get phase-randomized signal

    Args:
        data: Time series data, shape (n_samples,) or (n_samples, n_features)
        backend: Computation backend ('numpy' or 'torch').
            - 'numpy': CPU implementation using NumPy FFT (default, float64 precision)
            - 'torch': GPU implementation using PyTorch FFT (float32 precision, faster)
            - None: Defaults to 'numpy'
        random_state: Random seed for reproducibility

    Returns:
        Phase-randomized data with same shape as input

    Notes:
        - **CRITICAL**: Preserves power spectrum exactly (within numerical precision)
        - GPU acceleration: Use `backend='torch'` for GPU-accelerated FFT (5-20× faster for large data)
        - Precision: NumPy backend uses float64, PyTorch backend uses float32
        - Conjugate symmetry is maintained for real-valued output

    Examples:
        >>> x = np.sin(np.linspace(0, 10*np.pi, 100))  # Sine wave
        >>> x_rand = phase_randomize(x, random_state=42)
        >>> # Power spectrum preserved:
        >>> np.allclose(np.abs(np.fft.rfft(x))**2, np.abs(np.fft.rfft(x_rand))**2)
        True

        >>> # GPU acceleration for large datasets:
        >>> x_large = np.random.randn(10000)
        >>> x_rand_gpu = phase_randomize(x_large, backend='torch', random_state=42)
    """
    data = np.asarray(data)
    rng = check_random_state(random_state)

    # Handle GPU backend
    if backend == "torch":
        from nltools.backends import Backend

        backend_obj = Backend("torch")
        return _phase_randomize_gpu(data, backend_obj, rng)

    # Default: Use NumPy FFT (CPU)
    if backend is not None and backend != "numpy":
        import warnings

        warnings.warn(
            f"Unknown backend '{backend}'. Using 'numpy' as default.",
            UserWarning,
            stacklevel=2,
        )

    # Compute FFT
    fft_data = np.fft.fft(data, axis=0)
    n_samples = data.shape[0]

    # Determine positive and negative frequency indices
    if n_samples % 2 == 0:
        pos_freq = np.arange(1, n_samples // 2)
        neg_freq = np.arange(n_samples - 1, n_samples // 2, -1)
    else:
        pos_freq = np.arange(1, (n_samples - 1) // 2 + 1)
        neg_freq = np.arange(n_samples - 1, (n_samples - 1) // 2, -1)

    # Generate random phases and apply to FFT
    if data.ndim == 1:
        phase_shifts = rng.uniform(0, 2 * np.pi, size=len(pos_freq))
        fft_data[pos_freq] *= np.exp(1j * phase_shifts)
        fft_data[neg_freq] *= np.exp(-1j * phase_shifts)
    else:
        n_features = data.shape[1]
        phase_shifts = rng.uniform(0, 2 * np.pi, size=(len(pos_freq), n_features))
        fft_data[pos_freq, :] *= np.exp(1j * phase_shifts)
        fft_data[neg_freq, :] *= np.exp(-1j * phase_shifts)

    # Inverse FFT and return real part
    return np.real(np.fft.ifft(fft_data, axis=0))


def _circle_shift_gpu_batched(
    data: "torch.Tensor",
    shift_amounts: "torch.Tensor",
    backend: Backend,
) -> "torch.Tensor":
    """
    GPU-accelerated batched circular shift for time-series data.

    Processes multiple shifts simultaneously for efficiency. This is much faster
    than calling _circle_shift_gpu multiple times sequentially.

    Args:
        data: Time series data on GPU, shape (n_samples,)
        shift_amounts: Shift amounts for each permutation, shape (batch_size,)
        backend: Backend instance (must be PyTorch)

    Returns:
        Batched circularly shifted data, shape (batch_size, n_samples)
    """
    import torch

    if data.ndim != 1:
        raise ValueError(
            f"Batched circle_shift currently only supports 1D data, got shape {data.shape}"
        )

    n_samples = len(data)
    batch_size = len(shift_amounts)
    device = data.device

    # Create batch indices: (batch_size, n_samples)
    # For each batch item b, shift by shift_amounts[b]
    batch_indices = (
        torch.arange(n_samples, device=device).unsqueeze(0).expand(batch_size, -1)
    )
    shift_amounts_expanded = shift_amounts.unsqueeze(1)  # (batch_size, 1)

    # Apply circular shift: indices = (indices - shift) % n_samples
    shifted_indices = (batch_indices - shift_amounts_expanded) % n_samples

    # Use advanced indexing to get shifted data
    # data[shifted_indices] gives (batch_size, n_samples)
    return data[shifted_indices]


def _circle_shift_gpu(
    data: np.ndarray,
    shift_amount: Union[int, np.ndarray],
    backend: Backend,
) -> "np.ndarray | torch.Tensor":
    """
    GPU-accelerated circular shift for time-series data.

    Uses PyTorch advanced indexing for efficient batched circular shifts.
    Supports both 1D and 2D data.

    Args:
        data: Time series data on GPU, shape (n_samples,) or (n_samples, n_features)
        shift_amount: Shift amount(s)
            - For 1D: int specifying shift amount
            - For 2D: array of length n_features with shift per feature
        backend: Backend instance (must be PyTorch)

    Returns:
        Circularly shifted data with same shape as input (on GPU)
    """
    import torch

    # Handle 1D case
    if data.ndim == 1:
        shift_amount = int(shift_amount)
        n_samples = len(data)
        # Create circular indices
        indices = torch.arange(n_samples, device=data.device)
        indices = (indices - shift_amount) % n_samples
        return data[indices]

    # Handle 2D case
    elif data.ndim == 2:
        n_samples, n_features = data.shape
        shift_amount = torch.as_tensor(
            shift_amount, device=data.device, dtype=torch.long
        )

        if shift_amount.shape != (n_features,):
            raise ValueError(
                f"shift_amount must have length n_features={n_features}, "
                f"got shape {shift_amount.shape}"
            )

        # Shift each feature independently using torch.roll or manual indexing
        shifted = torch.empty_like(data)
        for i, shift in enumerate(shift_amount):
            shifted[:, i] = torch.roll(data[:, i], int(shift.item()))
        return shifted

    else:
        raise ValueError(f"data must be 1D or 2D, got shape {data.shape}")


def _phase_randomize_gpu(
    data: np.ndarray,
    backend: Backend,
    random_state,
) -> np.ndarray:
    """
    GPU-accelerated FFT-based phase randomization.

    Uses PyTorch FFT for efficient GPU computation. Preserves power spectrum
    exactly by randomizing phases while maintaining conjugate symmetry.

    Args:
        data: Time series data, shape (n_samples,) or (n_samples, n_features)
        backend: Backend instance (must be PyTorch)
        random_state: Random state instance for phase generation

    Returns:
        Phase-randomized data with same shape as input (on GPU, then converted to numpy)
    """
    import torch

    n_samples = data.shape[0]

    # Convert to float32 for GPU efficiency and transfer to device
    data_device = backend.to_device(data.astype(np.float32))

    # Compute FFT
    if data.ndim == 1:
        fft_data = torch.fft.fft(data_device)
    else:
        fft_data = torch.fft.fft(data_device, dim=0)

    # Determine positive and negative frequency indices
    if n_samples % 2 == 0:
        pos_freq = torch.arange(1, n_samples // 2, device=data_device.device)
        neg_freq = torch.arange(
            n_samples - 1, n_samples // 2, -1, device=data_device.device
        )
    else:
        pos_freq = torch.arange(1, (n_samples - 1) // 2 + 1, device=data_device.device)
        neg_freq = torch.arange(
            n_samples - 1, (n_samples - 1) // 2, -1, device=data_device.device
        )

    # Generate random phases on CPU (for reproducibility matching CPU version)
    if data.ndim == 1:
        phase_shifts = random_state.uniform(0, 2 * np.pi, size=len(pos_freq))
        phase_shifts = torch.as_tensor(
            phase_shifts, device=data_device.device, dtype=torch.float32
        )
        fft_data[pos_freq] *= torch.exp(1j * phase_shifts)
        fft_data[neg_freq] *= torch.exp(-1j * phase_shifts)
    else:
        n_features = data.shape[1]
        phase_shifts = random_state.uniform(
            0, 2 * np.pi, size=(len(pos_freq), n_features)
        )
        phase_shifts = torch.as_tensor(
            phase_shifts, device=data_device.device, dtype=torch.float32
        )
        fft_data[pos_freq, :] *= torch.exp(1j * phase_shifts)
        fft_data[neg_freq, :] *= torch.exp(-1j * phase_shifts)

    # Inverse FFT and return real part
    if data.ndim == 1:
        randomized = torch.fft.ifft(fft_data).real
    else:
        randomized = torch.fft.ifft(fft_data, dim=0).real

    # Convert back to numpy
    return backend.to_numpy(randomized)


def _phase_randomize_gpu_batched(
    data: "torch.Tensor",
    batch_seeds: np.ndarray,
    backend: Backend,
    random_state,
) -> "torch.Tensor":
    """
    GPU-accelerated batched FFT-based phase randomization.

    Processes multiple phase randomizations simultaneously for efficiency.
    Much faster than calling _phase_randomize_gpu multiple times sequentially.

    Args:
        data: Time series data on GPU, shape (n_samples,)
        batch_seeds: Random seeds for each permutation, shape (batch_size,)
        backend: Backend instance (must be PyTorch)
        random_state: Base random state instance

    Returns:
        Batched phase-randomized data, shape (batch_size, n_samples)
    """
    import torch

    if data.ndim != 1:
        raise ValueError(
            f"Batched phase_randomize currently only supports 1D data, got shape {data.shape}"
        )

    n_samples = len(data)
    batch_size = len(batch_seeds)
    device = data.device

    # Compute FFT once for all permutations
    fft_data = torch.fft.fft(data)  # (n_samples,)

    # Determine positive and negative frequency indices
    if n_samples % 2 == 0:
        pos_freq = torch.arange(1, n_samples // 2, device=device)
        neg_freq = torch.arange(n_samples - 1, n_samples // 2, -1, device=device)
    else:
        pos_freq = torch.arange(1, (n_samples - 1) // 2 + 1, device=device)
        neg_freq = torch.arange(n_samples - 1, (n_samples - 1) // 2, -1, device=device)

    n_pos_freq = len(pos_freq)

    # Generate random phases for all permutations in batch
    # Shape: (batch_size, n_pos_freq)
    phase_shifts = np.zeros((batch_size, n_pos_freq))
    for i, seed in enumerate(batch_seeds):
        perm_rng = np.random.RandomState(seed)
        phase_shifts[i] = perm_rng.uniform(0, 2 * np.pi, size=n_pos_freq)

    phase_shifts_device = torch.as_tensor(
        phase_shifts, device=device, dtype=torch.float32
    )  # (batch_size, n_pos_freq)

    # Expand fft_data to batch dimension: (batch_size, n_samples)
    fft_data_batch = fft_data.unsqueeze(0).expand(batch_size, -1).clone()

    # Apply phase shifts: fft_data[pos_freq] *= exp(1j * phase_shifts)
    # Broadcasting: (batch_size, n_pos_freq) applied to (batch_size, n_samples)
    fft_data_batch[:, pos_freq] *= torch.exp(1j * phase_shifts_device)
    # For negative frequencies, need to flip phase_shifts to match neg_freq order
    # neg_freq is in reverse order, so we flip phase_shifts
    fft_data_batch[:, neg_freq] *= torch.exp(-1j * phase_shifts_device.flip(dims=[1]))

    # Inverse FFT and return real part
    randomized = torch.fft.ifft(fft_data_batch, dim=1).real  # (batch_size, n_samples)

    return randomized


def _timeseries_correlation_permutation_gpu_batched(
    data1: np.ndarray,
    data2: np.ndarray,
    method: Literal["circle_shift", "phase_randomize"],
    n_permute: int,
    metric: Literal["pearson", "spearman", "kendall"],
    tail: int,
    return_null: bool,
    backend: Backend,
    max_gpu_memory_gb: float,
    random_state,
) -> dict:
    """
    Time-series correlation permutation test using GPU with automatic batching.

    Processes permutations in batches to avoid GPU OOM. Transfers data once
    and reuses across batches for efficiency.

    Args:
        data1: First time series, shape (n_samples,)
        data2: Second time series, shape (n_samples,)
        method: Permutation method ('circle_shift' or 'phase_randomize')
        n_permute: Number of permutations
        metric: Correlation type ('pearson', 'spearman', 'kendall')
        tail: Test type (1 or 2)
        return_null: Whether to return null distribution
        backend: Backend instance (must be PyTorch)
        max_gpu_memory_gb: Maximum GPU memory budget
        random_state: Random state instance

    Returns:
        dict: Same format as main function, with 'backend' indicating GPU device
    """
    import torch
    from tqdm import tqdm

    n_samples = len(data1)

    # Convert to float32 for GPU efficiency
    data1 = data1.astype(np.float32)
    data2 = data2.astype(np.float32)

    # Select correlation function
    if metric == "pearson":
        corr_func = _pearson_correlation
    elif metric == "spearman":
        corr_func = _spearman_correlation
    else:  # kendall
        corr_func = _kendall_correlation

    # Compute observed correlation
    obs_corr = corr_func(data1, data2)
    if isinstance(obs_corr, np.ndarray):
        obs_corr = obs_corr[0]
    obs_corr = np.asarray(obs_corr)

    # Determine batch size based on memory budget
    # Memory bottleneck: permuted data and correlation computation
    # For circle_shift: (batch_size, n_samples) tensors
    # For phase_randomize: FFT buffers + permuted data
    batch_size, n_batches = _auto_batch_size(
        n_permute, n_samples, 1, max_memory_gb=max_gpu_memory_gb
    )

    # Transfer data to device once (reused across batches)
    data1_device = backend.to_device(data1)

    # Accumulate null distribution across batches
    null_dist_list = []

    # Process permutations in batches with progress bar
    pbar = tqdm(
        total=n_permute,
        desc="GPU timeseries perms",
        unit="perm",
        disable=n_batches == 1,
    )

    for batch_idx in range(n_batches):
        # Determine current batch size
        start_idx = batch_idx * batch_size
        end_idx = min(start_idx + batch_size, n_permute)
        current_batch_size = end_idx - start_idx

        # Pre-generate seeds for this batch (deterministic)
        MAX_INT = 2**31 - 1
        batch_seeds = random_state.randint(MAX_INT, size=current_batch_size)

        # Generate permuted data1 for this batch using batched operations
        if method == "circle_shift":
            # Generate random shift amounts for all permutations in batch
            shift_amounts = np.array(
                [
                    np.random.RandomState(batch_seeds[i]).choice(np.arange(n_samples))
                    for i in range(current_batch_size)
                ]
            )
            shift_amounts_device = backend.to_device(shift_amounts.astype(np.int64))
            if backend.name.startswith("torch"):
                shift_amounts_device = shift_amounts_device.long()

            # Batched circle shift: (batch_size, n_samples)
            perm_data1_batch = _circle_shift_gpu_batched(
                data1_device, shift_amounts_device, backend
            )
        else:  # phase_randomize
            # Batched phase randomization: (batch_size, n_samples)
            perm_data1_batch = _phase_randomize_gpu_batched(
                data1_device, batch_seeds, backend, random_state
            )

        # Compute correlations for all permutations in batch simultaneously
        # Vectorize correlation computation
        perm_data1_np = backend.to_numpy(perm_data1_batch)  # (batch_size, n_samples)

        # Use correlation function that handles 2D input (batch dimension)
        batch_corrs = []
        for i in range(current_batch_size):
            corr = corr_func(perm_data1_np[i], data2)
            batch_corrs.append(corr[0] if isinstance(corr, np.ndarray) else corr)

        batch_corrs = np.array(batch_corrs)
        null_dist_list.append(batch_corrs)

        # Update progress bar
        pbar.update(current_batch_size)

        # Free batch memory
        del perm_data1_batch, perm_data1_np, batch_corrs
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    pbar.close()

    # Combine batches: (n_permute,)
    null_dist = np.concatenate(null_dist_list)

    # Compute p-value
    p_value = _compute_pvalue(obs_corr, null_dist, tail=tail)

    # Build result
    result = {
        "correlation": float(obs_corr),
        "p": p_value.item() if hasattr(p_value, "item") else float(p_value),
        "parallel": "gpu",
    }

    if return_null:
        result["null_dist"] = null_dist

    return result


def timeseries_correlation_permutation_test(
    data1: np.ndarray,
    data2: np.ndarray,
    method: Literal["circle_shift", "phase_randomize"] = "circle_shift",
    n_permute: int = 5000,
    metric: Literal["pearson", "spearman", "kendall"] = "pearson",
    tail: int = 2,
    parallel: Optional[str] = "cpu",
    n_jobs: int = -1,
    max_gpu_memory_gb: float = 4.0,
    return_null: bool = False,
    random_state: Optional[Union[int, np.random.RandomState]] = None,
) -> dict:
    """
    Time-series correlation permutation test.

    Unlike standard permutation tests that shuffle data independently,
    this test uses time-series-aware permutation methods that preserve
    temporal structure (circle_shift) or power spectrum (phase_randomize).

    Use this test when data contains temporal autocorrelation. Standard
    permutation tests inflate Type I error for autocorrelated data.

    Args:
        data1: First time series, shape (n_samples,) or (n_samples, 1)
        data2: Second time series, shape (n_samples,) or (n_samples, 1)
        method: Permutation method:
            - 'circle_shift': Circular shift (preserves autocorrelation)
            - 'phase_randomize': FFT-based (preserves power spectrum)
        n_permute: Number of permutations
        metric: Correlation type ('pearson', 'spearman', 'kendall')
        tail: Test type (1=one-tailed, 2=two-tailed)
        parallel: Parallelization method (default: 'cpu')
            - None: Single-threaded NumPy (for debugging/small problems)
            - 'cpu': CPU parallelization via joblib (default, 4-8× speedup)
            - 'gpu': GPU acceleration via PyTorch (fastest for large problems)
        n_jobs: Number of parallel jobs (-1 = all cores)
            Only used when parallel='cpu'
        max_gpu_memory_gb: Maximum GPU memory to use in GB (default: 4.0)
            Controls automatic batching to prevent OOM errors. Only used with
            parallel='gpu'. Larger values allow more permutations per batch but
            risk OOM on smaller GPUs.
        return_null: Whether to return null distribution
        random_state: Random seed for reproducibility

    Returns:
        Dictionary with keys:
            - 'correlation': Observed correlation coefficient
            - 'p': P-value
            - 'null_dist': (if return_null=True) Null distribution
            - 'parallel': Parallelization method used

    Examples:
        >>> x = np.sin(np.linspace(0, 10*np.pi, 100))
        >>> y = np.cos(np.linspace(0, 10*np.pi, 100))
        >>> result = timeseries_correlation_permutation_test(
        ...     x, y, method='circle_shift', n_permute=1000, random_state=42
        ... )
        >>> result['correlation']  # Strong negative correlation
        -0.999...
        >>> result['p'] < 0.05  # Significant
        True

        >>> # GPU acceleration
        >>> result = timeseries_correlation_permutation_test(
        ...     x, y, method='phase_randomize', parallel='gpu', n_permute=5000
        ... )

    Notes:
        - Default (parallel='cpu'): CPU parallelization with joblib (4-8× speedup)
        - GPU parallelization ('gpu'): 5-20× faster for large problems (n_samples > 1000)
        - Single-threaded (parallel=None): Use for small problems or debugging
        - For independent data, use regular correlation_permutation_test
        - circle_shift is faster and suitable for most fMRI time series
        - phase_randomize preserves power spectrum exactly (tests nonlinearity)
        - Only data1 is randomized; data2 remains fixed to test correlation
        - phase_randomize benefits most from GPU (FFT acceleration)
    """
    # Validate parallel parameter
    if parallel not in [None, "cpu", "gpu"]:
        raise ValueError(f"parallel must be None, 'cpu', or 'gpu', got {parallel!r}")

    # Validate inputs
    data1 = np.asarray(data1).squeeze()
    data2 = np.asarray(data2).squeeze()

    if data1.ndim != 1 or data2.ndim != 1:
        raise ValueError("data1 and data2 must be 1D arrays")

    if len(data1) != len(data2):
        raise ValueError("data1 and data2 must have the same length")

    if method not in ["circle_shift", "phase_randomize"]:
        raise ValueError(
            f"method must be 'circle_shift' or 'phase_randomize', got '{method}'"
        )

    if metric not in ["pearson", "spearman", "kendall"]:
        raise ValueError(
            f"metric must be 'pearson', 'spearman', or 'kendall', got '{metric}'"
        )

    # Select correlation function
    if metric == "pearson":
        corr_func = _pearson_correlation
    elif metric == "spearman":
        corr_func = _spearman_correlation
    else:  # kendall
        corr_func = _kendall_correlation

    # Compute observed correlation
    obs_corr = corr_func(data1, data2)
    if isinstance(obs_corr, np.ndarray):
        obs_corr = obs_corr[0]
    obs_corr = np.asarray(obs_corr)

    # Decide execution mode based on parallel parameter
    if parallel == "cpu" or parallel is None:
        # CPU modes
        if parallel is None:
            # Single-threaded NumPy
            rng = check_random_state(random_state)
            MAX_INT = 2**31 - 1
            seeds = rng.randint(MAX_INT, size=n_permute)

            if method == "circle_shift":
                null_dist = []
                for seed in seeds:
                    perm_data1 = circle_shift(data1, random_state=seed)
                    corr = corr_func(perm_data1, data2)
                    null_dist.append(corr[0] if isinstance(corr, np.ndarray) else corr)
            else:  # phase_randomize
                null_dist = []
                for seed in seeds:
                    perm_data1 = phase_randomize(data1, random_state=seed)
                    corr = corr_func(perm_data1, data2)
                    null_dist.append(corr[0] if isinstance(corr, np.ndarray) else corr)

            null_dist = np.array(null_dist)
            p_value = _compute_pvalue(obs_corr, null_dist, tail=tail)

            results = {
                "correlation": float(obs_corr),
                "p": p_value.item() if hasattr(p_value, "item") else float(p_value),
                "parallel": None,
            }

            if return_null:
                results["null_dist"] = null_dist

            return results
        else:
            # CPU parallelization mode (existing implementation)
            # Setup random state and generate seeds for workers
            rng = check_random_state(random_state)
            MAX_INT = 2**31 - 1
            seeds = rng.randint(MAX_INT, size=n_permute)

            # Define worker function
            from joblib import Parallel, delayed
            from tqdm import tqdm

            if method == "circle_shift":

                def _compute_one_perm(seed):
                    """Compute correlation for one circle_shift permutation."""
                    perm_data1 = circle_shift(data1, random_state=seed)
                    corr = corr_func(perm_data1, data2)
                    return corr[0] if isinstance(corr, np.ndarray) else corr

            else:  # phase_randomize

                def _compute_one_perm(seed):
                    """Compute correlation for one phase_randomize permutation.

                    Note: Only data1 is phase-randomized to test correlation significance.
                    Randomizing both variables reduces power and is conceptually incorrect
                    for testing H0: correlation = 0.
                    """
                    perm_data1 = phase_randomize(data1, random_state=seed)
                    # data2 unchanged - this destroys correlation under H0
                    corr = corr_func(perm_data1, data2)
                    return corr[0] if isinstance(corr, np.ndarray) else corr

            # Execute in parallel with progress bar
            null_dist = Parallel(n_jobs=n_jobs)(
                delayed(_compute_one_perm)(seeds[i])
                for i in tqdm(range(n_permute), desc=f"{method} perms", unit="perm")
            )
            null_dist = np.array(null_dist)

            # Compute p-value
            p_value = _compute_pvalue(obs_corr, null_dist, tail=tail)

            # Prepare results (convert to Python scalars for consistency with stats.py)
            results = {
                "correlation": float(obs_corr),
                "p": p_value.item() if hasattr(p_value, "item") else float(p_value),
                "parallel": "cpu",
            }

            if return_null:
                results["null_dist"] = null_dist

            return results
    else:
        # GPU mode
        backend_obj = Backend("torch")
        rng = check_random_state(random_state)
        return _timeseries_correlation_permutation_gpu_batched(
            data1,
            data2,
            method,
            n_permute,
            metric,
            tail,
            return_null,
            backend_obj,
            max_gpu_memory_gb,
            rng,
        )
