"""Shared helpers for DesignMatrix submodules.

These are internal utilities used by the facade and submodules — not part of the
public API.
"""

from __future__ import annotations

import functools
import re
from typing import TYPE_CHECKING

import polars as pl

from nltools.utils import is_reserved_name, parse_run_separated, strip_reserved_prefix

if TYPE_CHECKING:
    from nltools.data.designmatrix import DesignMatrix


WRAP_AS_DESIGNMATRIX = frozenset({"slice", "filter", "select"})

# Drift terms generated by add_poly / add_dct_basis, matched on the base name
# left after the run prefix is stripped (e.g. '.nl_r1_poly_0' -> 'poly_0').
_DRIFT_BASE_RE = re.compile(r"(?:poly|cosine)_\d+")
_INTERCEPT_BASE_RE = re.compile(r"(?:poly|cosine)_0")


def is_generated_intercept(name: str) -> bool:
    """Return True if ``name`` is an intercept column nltools generated.

    Covers the zeroth-order drift terms from `add_poly` / `add_dct_basis`
    (``.nl_poly_0`` / ``.nl_cosine_0``) and their run-separated variants. Both
    are all-ones columns, so anything computing a correlation matrix has to
    drop them. Keyed on the reserved namespace: a user column is never an
    intercept by this definition, however it happens to be named.
    """
    if not is_reserved_name(name):
        return False
    parsed = parse_run_separated(name)
    base = parsed[1] if parsed is not None else strip_reserved_prefix(name)
    return _INTERCEPT_BASE_RE.fullmatch(base) is not None


def has_run_separated_drift(dm: DesignMatrix) -> bool:
    """Return True if ``dm`` carries per-run polynomial or cosine drift terms.

    Adding a global drift term to a design that already models drift per run
    is ambiguous, so both `add_poly` and `add_dct_basis` refuse it. Detection
    keys on the reserved namespace nltools controls (``.nl_r{run}_poly_{i}`` /
    ``.nl_r{run}_cosine_{i}``), so a user confound is never mistaken for one
    however it is named.
    """
    for col in dm.confounds or []:
        parsed = parse_run_separated(col)
        if parsed is not None and _DRIFT_BASE_RE.fullmatch(parsed[1]):
            return True
    return False


def df_passthrough(dm: DesignMatrix, name: str):
    """Resolve ``name`` on ``dm.data``; re-wrap DataFrame results for allowlisted methods.

    Used by ``DesignMatrix.__getattr__`` to expose polars' DataFrame API without
    duplicating every method. Row-preserving ops in ``WRAP_AS_DESIGNMATRIX`` return
    a new ``DesignMatrix`` with metadata copied via ``copy_with``; everything else
    returns the raw polars object.
    """
    attr = getattr(dm.data, name)
    if not callable(attr) or name not in WRAP_AS_DESIGNMATRIX:
        return attr

    @functools.wraps(attr)  # nosemgrep: kwargs-internal-forwarding  # generic wrapper
    def wrapped(*args, **kwargs):
        result = attr(*args, **kwargs)
        if isinstance(result, pl.DataFrame):
            return copy_with(dm, result)
        return result

    return wrapped


def copy_with(
    dm: DesignMatrix,
    new_df: pl.DataFrame,
    **metadata_updates,
) -> DesignMatrix:
    """Create a new DesignMatrix with updated data and metadata.

    This is the core pattern for immutable transformations.
    All methods that transform data should use this helper.

    Args:
        dm (DesignMatrix): Source DesignMatrix whose metadata to copy.
        new_df (pl.DataFrame): New underlying data.
        **metadata_updates (dict): Metadata attributes to override
            (e.g. ``convolved=['stim']``).

    Returns:
        DesignMatrix: New DesignMatrix with updated data and metadata.
    """
    from nltools.data.designmatrix import DesignMatrix

    # Start with current metadata, apply caller overrides
    metadata = get_metadata(dm)
    metadata.update(metadata_updates)

    # Prune column-name metadata against the new frame so that ops which drop
    # columns (select, __getitem__ with a list) don't leave dangling references.
    new_cols = set(new_df.columns)
    metadata["convolved"] = [c for c in metadata["convolved"] if c in new_cols]
    metadata["confounds"] = [c for c in metadata["confounds"] if c in new_cols]

    new_dm = DesignMatrix(
        new_df,
        sampling_freq=metadata["sampling_freq"],
        convolved=metadata["convolved"],
        confounds=metadata["confounds"],
        # A column-less result still describes the source's timepoints: carry
        # the recorded length, or fall back to the source's height when the
        # transform is what emptied it.
        n_rows=(metadata["n_rows"] or dm.shape[0] or None)
        if new_df.width == 0
        else None,
    )
    new_dm.multi = metadata["multi"]

    return new_dm


def get_metadata(dm: DesignMatrix) -> dict:
    """Extract metadata as a dict (for copying).

    Args:
        dm (DesignMatrix): DesignMatrix instance.

    Returns:
        dict: Dictionary with keys 'sampling_freq', 'convolved', 'confounds',
            'multi', 'n_rows'.
    """
    return {
        "sampling_freq": dm.sampling_freq,
        "convolved": dm.convolved.copy(),
        "confounds": dm.confounds.copy(),
        "multi": dm.multi,
        "n_rows": dm._n_rows,
    }


def get_data_columns(dm: DesignMatrix, exclude_confounds: bool = True) -> list[str]:
    """Get column names, optionally excluding confound regressors.

    Used wherever experimental regressors must be distinguished from
    nuisance/confound columns (polynomial drift, DCT cosines, motion, etc.).

    Args:
        dm (DesignMatrix): DesignMatrix instance.
        exclude_confounds (bool): If True, exclude nuisance columns tracked in
            ``dm.confounds`` from the result. Default: True.

    Returns:
        list[str]: Column names (excluding confounds if requested).
    """
    if exclude_confounds and dm.confounds:
        return [col for col in dm.columns if col not in dm.confounds]
    return list(dm.columns)
