"""Cross-cutting utilities used across the nltools package."""

__all__ = [
    "RESERVED_PREFIX",
    "DesignMatrixWarning",
    "ResamplingWarning",
    "all_same",
    "attempt_to_import",
    "coalesced_gc",
    "concatenate",
    "find_stack_level",
    "get_resource_path",
    "is_reserved_name",
    "make_progress_bar",
    "maybe_tqdm",
    "parse_run_separated",
    "reserved_name",
    "run_separated_name",
]

import collections
import contextlib
import gc
import inspect
import os
import re
from contextlib import contextmanager
from os.path import dirname, join, sep as pathsep

import numpy as np


# ---------------------------------------------------------------------------
# Reserved column namespace
# ---------------------------------------------------------------------------

RESERVED_PREFIX = ".nl_"
"""Prefix marking a column name generated by nltools rather than the user.

Every column nltools invents — polynomial drift (`.nl_poly_0`), DCT cosine
bases (`.nl_cosine_1`), spike indicators (`.nl_global_spike1`), and the
run-separated variants produced by a multi-run `DesignMatrix.append` — carries
this prefix. Machinery that needs to recognize its own columns keys on the
prefix, never on heuristics over user-controlled names (underscore counts,
substring matches), so users may name their own regressors anything without
colliding with nltools internals.
"""

_RUN_SEPARATED_RE = re.compile(re.escape(RESERVED_PREFIX) + r"r(\d+)_(.+)")


def reserved_name(base: str) -> str:
    """Build a generated column name inside the reserved namespace.

    Args:
        base: Name without the reserved prefix, e.g. ``'poly_0'``.

    Returns:
        str: `base` prefixed with `RESERVED_PREFIX`, idempotently — a name
            that already carries the prefix is returned unchanged.
    """
    return base if is_reserved_name(base) else f"{RESERVED_PREFIX}{base}"


def is_reserved_name(name: str) -> bool:
    """Return True if ``name`` is in the nltools-generated column namespace."""
    return name.startswith(RESERVED_PREFIX)


def strip_reserved_prefix(name: str) -> str:
    """Return ``name`` without its reserved prefix (a no-op if it has none)."""
    return name[len(RESERVED_PREFIX) :] if is_reserved_name(name) else name


def run_separated_name(run_idx: int, name: str) -> str:
    """Build the run-separated variant of a column name.

    Run separation is an nltools-generated naming decision, so the result
    always lands in the reserved namespace regardless of whether the source
    column was user-named (``motion_x`` → ``.nl_r0_motion_x``) or already
    generated (``.nl_poly_0`` → ``.nl_r0_poly_0``; prefixes never stack).

    Args:
        run_idx: Zero-based run index.
        name: Column name to separate.

    Returns:
        str: ``.nl_r{run_idx}_{base}``.
    """
    return f"{RESERVED_PREFIX}r{run_idx}_{strip_reserved_prefix(name)}"


def parse_run_separated(name: str) -> tuple[int, str] | None:
    """Split a run-separated column name into its run index and base name.

    Args:
        name: Column name to parse.

    Returns:
        tuple[int, str] | None: `(run_idx, base)` for a run-separated name (e.g.
            `'.nl_r1_poly_0'` → `(1, 'poly_0')`), else None.
    """
    match = _RUN_SEPARATED_RE.fullmatch(name)
    return (int(match.group(1)), match.group(2)) if match else None


# ---------------------------------------------------------------------------
# Warnings: attribution and library-wide categories
# ---------------------------------------------------------------------------

_PACKAGE_DIR = dirname(__file__) + pathsep
_TESTS_DIR = join(_PACKAGE_DIR, "tests") + pathsep
# ``@coalesced_gc()`` (a contextmanager used as a decorator) wraps facade
# methods in a stdlib contextlib frame; it is nltools plumbing, not user code.
_PLUMBING_FILES = frozenset({contextlib.__file__})


def _is_library_frame(filename: str) -> bool:
    if filename in _PLUMBING_FILES:
        return True
    return filename.startswith(_PACKAGE_DIR) and not filename.startswith(_TESTS_DIR)


def find_stack_level() -> int:
    """Return the ``stacklevel`` that attributes a warning to the caller's code.

    Walks up from the caller until the first frame outside the nltools package
    (``nltools/tests/`` counts as outside: tests are the library's users; the
    stdlib ``contextlib`` frame that ``@coalesced_gc()`` inserts counts as
    inside), so a ``warnings.warn`` deep inside a facade lands on the user's
    line rather than on nltools internals — the same pattern nilearn and pandas
    use. Every ``warnings.warn`` in the library passes
    ``stacklevel=find_stack_level()``; a source-scan test enforces it.

    Returns:
        int: Value for the ``stacklevel`` argument of ``warnings.warn``.

    Examples:
        ```python
        warnings.warn("message", UserWarning, stacklevel=find_stack_level())
        ```
    """
    frame = inspect.currentframe()
    level = 0
    try:
        while frame is not None and _is_library_frame(inspect.getfile(frame)):
            frame = frame.f_back
            level += 1
    finally:
        del frame
    return level


class ResamplingWarning(UserWarning):
    """Data is (or will be) resampled to a different space than it arrived in.

    Raised when a data image does not match the mask/template it is loaded
    against — a detected template at another resolution, or a mask in a
    different space — and nltools resamples to reconcile them. Subclasses
    ``UserWarning`` so it participates in default filtering while staying
    individually silenceable:
    ``warnings.filterwarnings("ignore", category=ResamplingWarning)``.
    """


class DesignMatrixWarning(UserWarning):
    """A ``DesignMatrix`` operation was a no-op or partially skipped.

    Raised by regressor builders (``add_poly``, ``add_dct_basis``,
    ``convolve``) when the requested columns already exist and are skipped.
    Subclasses ``UserWarning`` so it participates in default filtering while
    staying individually silenceable:
    ``warnings.filterwarnings("ignore", category=DesignMatrixWarning)``.
    """


# ---------------------------------------------------------------------------
# Cross-cutting helpers (used by multiple subsystems)
# ---------------------------------------------------------------------------


@contextmanager
def coalesced_gc():
    """Collapse nilearn's forced per-copy `gc.collect()` calls into one per operation.

    nilearn runs a full `gc.collect()` after every masked-array copy it makes; a
    masking-heavy operation — a GLM fit that re-validates the same mask and
    builds several result maps — fires dozens. With torch/nilearn/sklearn
    resident each sweep costs ~0.1s, so the storm dominates the wall-clock of
    otherwise-trivial numerical work.

    This no-ops the interim collects and runs a single real collect on exit,
    so peak memory stays bounded to one operation's worth of cyclic garbage
    (nilearn's collect is a peak-memory optimization, not a correctness
    requirement — suppressing it only defers reclamation). Opt out with
    `NLTOOLS_NO_GC_COALESCE=1`.

    Because `@contextmanager` results double as decorators, this can also be
    used as `@coalesced_gc()` on an operation-boundary method.

    Nesting is safe: each frame restores whatever it saved, so only the
    outermost frame restores the real `gc.collect` and runs the final sweep;
    inner frames' exit-time collect is a no-op.

    Caveat: this swaps a process-global builtin. It is safe under the default
    loky (process) worker backend — each worker has its own `gc`. Under a
    *threading* backend there is a brief window where a concurrent thread sees
    the no-op collect; `NLTOOLS_NO_GC_COALESCE=1` is the escape hatch there.
    """
    if os.environ.get("NLTOOLS_NO_GC_COALESCE"):
        yield
        return
    saved = gc.collect  # may already be the no-op if we're nested
    gc.collect = lambda *a, **k: 0
    try:
        yield
    finally:
        gc.collect = saved  # only the outermost frame restores the real collect
        gc.collect()  # no-op if still nested; one real sweep at the top


def get_resource_path():
    """Get the path to the nltools resource directory.

    Returns:
        str: Absolute path to `nltools/resources/`, with a trailing separator.
    """
    return join(dirname(__file__), "resources") + pathsep


module_names = {}
Dependency = collections.namedtuple("Dependency", "package value")


def attempt_to_import(dependency, name=None, fromlist=None):
    """Attempt to import an optional dependency, returning None if unavailable.

    This function is used to handle optional dependencies gracefully. If the
    import fails, the function returns None rather than raising an error,
    allowing the calling code to check and handle missing dependencies.

    Args:
        dependency (str): The module name to import (e.g. `'torch'`, `'cupy'`).
        name (str, optional): Key to record the dependency under in the module-level
            `module_names` registry. Defaults to `dependency`.
        fromlist (list[str], optional): Names to import from the module (passed to
            `__import__`).

    Returns:
        ModuleType | None: The imported module, or None if the import failed.

    Examples:
        ```python
        torch = attempt_to_import("torch")
        if torch is not None:
            ...  # use torch
        ```
    """
    if name is None:
        name = dependency
    try:
        mod = __import__(dependency, fromlist=fromlist)
    except ImportError:
        mod = None
    module_names[name] = Dependency(dependency, mod)
    return mod


def all_same(items):
    """Check if all items in a sequence are equal to the first item.

    Args:
        items (Sequence): Items to compare (arrays are compared element-wise).

    Returns:
        bool: True if all items equal the first item, False otherwise.

    Examples:
        ```python
        all_same([1, 1, 1])  # → True
        all_same([1, 2, 1])  # → False
        ```
    """
    return all(np.array_equal(x, items[0]) for x in items)


def concatenate(data):
    """Concatenate a list of `BrainData` or `Adjacency` objects.

    Args:
        data (list[BrainData] | list[Adjacency]): Objects to concatenate; all must
            be of the same class.

    Returns:
        BrainData | Adjacency: A single object holding every input in order.

    Raises:
        ValueError: If `data` is not a list or mixes classes.
    """

    if not isinstance(data, list):
        raise ValueError("Make sure you are passing a list of objects.")

    if all(isinstance(x, data[0].__class__) for x in data):
        out = data[0].__class__()
        for i in data:
            out = out.append(i)
    else:
        raise ValueError("Make sure all objects in the list are the same type.")
    return out


# ---------------------------------------------------------------------------
# Progress bars — the single library-wide mechanism
# ---------------------------------------------------------------------------


class _NullProgressBar:
    """No-op stand-in for `tqdm` used when `progress_bar=False`.

    Supports the subset of the tqdm interface nltools relies on, so call sites
    that drive a bar manually need no branching.
    """

    def update(self, n: int = 1) -> None:
        pass

    def close(self) -> None:
        pass

    def set_postfix(self, *args, **kwargs) -> None:
        pass

    def set_description(self, *args, **kwargs) -> None:
        pass

    def __enter__(self) -> "_NullProgressBar":
        return self

    def __exit__(self, *exc_info) -> bool:
        return False


def maybe_tqdm(iterable, *, progress_bar: bool, **tqdm_kwargs):
    """Wrap `iterable` in a tqdm progress bar only when `progress_bar` is True.

    tqdm writes to stderr, so an unconditional bar makes functions noisy when
    called in a loop (a 100-iteration calibration study would emit 100 bars).
    Importing tqdm lazily also keeps it off the import path when unused. Uses
    `tqdm.auto`, so notebooks get widget bars and terminals get text bars.

    Args:
        iterable (Iterable): The iterable to wrap.
        progress_bar (bool): Whether to display a progress bar.
        **tqdm_kwargs (dict): Forwarded to `tqdm` (e.g. `desc`, `unit`, `total`).

    Returns:
        Iterable: The original iterable, or a `tqdm`-wrapped version of it.

    Examples:
        ```python
        for i in maybe_tqdm(range(n_permute), progress_bar=progress_bar,
                            desc="CPU parallel perms", unit="perm"):
            ...
        ```
    """
    if not progress_bar:
        return iterable

    from tqdm.auto import tqdm

    return tqdm(iterable, **tqdm_kwargs)


def make_progress_bar(*, progress_bar: bool, **tqdm_kwargs):
    """Build a progress bar, or a no-op stand-in when `progress_bar` is False.

    Use this for call sites that drive the bar manually via `.update()` rather
    than by iteration. Uses `tqdm.auto`, so notebooks get widget bars and
    terminals get text bars.

    Args:
        progress_bar (bool): Whether to display a progress bar.
        **tqdm_kwargs (dict): Forwarded to `tqdm` (e.g. `total`, `desc`, `unit`).

    Returns:
        tqdm | _NullProgressBar: A `tqdm` instance, or a `_NullProgressBar` exposing
            the same subset of its interface (`update`, `close`, `set_postfix`,
            `set_description`, and the context-manager protocol).
    """
    if not progress_bar:
        return _NullProgressBar()

    from tqdm.auto import tqdm

    return tqdm(**tqdm_kwargs)


def resolve_threshold(value, data):
    """Resolve a threshold spec — a number or a percentile string — to a float.

    The single source of truth for what `"98%"` means across the library
    (`BrainData.threshold` and `BrainData.iplot` both route through it).
    Numbers and None pass through unchanged. A percentile string is resolved
    against the **finite nonzero** values of `data`: on a masked stat map
    most voxels are exactly zero (absence of data), and including them drags
    every percentile toward zero.

    Args:
        value: A number (returned as-is), None (returned as-is), or a string
            like `"98%"`.
        data: Array-like the percentile is computed over. Callers choose the
            frame of reference — e.g. `iplot` passes magnitudes
            (`np.abs(data)`) because its window is a magnitude window, while
            `threshold` passes signed values.

    Returns:
        float | None: The resolved threshold.

    Raises:
        ValueError: If `value` is a string without a trailing `%`.
    """
    import numpy as np

    if value is None or not isinstance(value, str):
        return value
    if not value.endswith("%"):
        raise ValueError(
            f"string threshold must be a percentile like '98%', got {value!r}"
        )
    pct = float(value[:-1])
    vals = np.asarray(data, dtype=float).ravel()
    vals = vals[np.isfinite(vals)]
    vals = vals[vals != 0]
    if vals.size == 0:
        return 0.0
    return float(np.percentile(vals, pct))
